# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/openjdk:11-jdk
      - image: azul/zulu-openjdk:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install tools
      - run: apt-get update -y
      - run: apt-get install -y unzip wget

      # about Gradle
      - run: ./gradlew --version

      # about Gradle
      - run: ./gradlew --version

      - run:
          name: "Check project libraries"
          command: |
            cp ./jcenter.properties.sample $HOME/jcenter.properties
            ./gradlew check
            ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: 
          name: "run application on project"
          command: ./gradlew -q app:run
      
      - run:
          name: "run application on Local OS System"
          command: |
            ./gradlew app:installDist
            ./app/build/install/app/bin/basic_118

      - run:
          name: "get the library package from JCenter"
          command: |
            wget https://jcenter.bintray.com/de/iotoi/basic_118/0.118.1/basic_118-0.118.1.jar
