# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  project_build:
    docker:
      # specify the version you desire here
      #- image: circleci/openjdk:11-jdk
      - image: azul/zulu-openjdk:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # run Java Version
      - run: java --version
      - run: java -version

      - run: 
          name: install tools
          command: |
            whoami
            cat /etc/*-release
            apt update -y
            apt install screen netcat -y
            screen –version

      - run:
          name: "Run The Web Application with Gradle"
          command: |
              ./gradlew -q check
              screen -d -m -s "webapp_on_project" ./gradlew -q bootRun

  docker_build:
    machine: true
      # image: ubuntu-2004:202010-01

    steps:      
      - checkout

      - run: 
          name: "install tools"
          command: |
            cat /etc/*-release
            sudo apt update -y
            sudo apt install curl wget netcat -y

      - run:
          name: "start web server with web app"
          command: |
              ./gradlew bootBuildImage --imageName=gradle_kotlin/basic_xxx
              docker run -d --name=xxx_gradle_java_container -p 80:8080 gradle_kotlin/basic_xxx

      - run:
          name: "browse the website"
          command: |
              sleep 10 && nc -vz localhost 80
              curl http://127.0.0.1:80/ | json_pp

      - run:
          name: "stop web server on docker"
          command: |
              docker stop xxx_gradle_kotlin_container

workflows:
  build:
    jobs:
      - project_build
      - docker_build