version: 2.1

defaults: &defaults
  docker:
    - image: jetty:9.4.35-jdk11
      user: root
    # https://stackoverflow.com/questions/50320263/change-user-on-circleci
    # https://blog.sshn.me/posts/circleci-change-user/
    # https://circleci.com/blog/how-to-do-vulnerability-management-with-docker-and-ci-cd/

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

  steps:      
    # Download and cache dependencies
    # https://circleci.com/docs/2.0/caching/
    - restore_cache:
        keys:
        - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
        - gradle-repo-v1-{{ .Branch }}-
        - gradle-repo-v1-

    - save_cache:
        paths:
          - ~/.gradle
        key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

jobs:
  project_build:
    <<: *defaults
    steps:      
      - checkout

      # install tool screen
      - run: 
          name: install tool screen
          command: |
            whoami
            cat /etc/*-release
            apt update -y
            apt install screen -y
            screen –version

      # /var/lib/jetty/repo
      - run: pwd
      # /var/lib/jetty/repo/build.gradle
      - run: ls -al .

      - run:
          name: "build application"
          command: |
            whoami
            cp ./jcenter.properties.sample ~/jcenter.properties
            ./gradlew clean build

      - run:
          name: "start webapp on project"
          command: |
            screen -d -m -s "webapp_on_project" ./gradlew appRun

  local_build:
    <<: *defaults
    steps:      
      - checkout
  
      # install tool screen
      - run: 
          name: install tool screen
          command: |
            whoami
            cat /etc/*-release
            apt update -y
            apt install screen -y
            screen –version

      - run:
          name: "build application"
          command: |
            whoami
            cp ./jcenter.properties.sample ~/jcenter.properties
            ./gradlew clean build

      - run:
          name: "archives all configured gretty products"
          command: |
            ./gradlew archiveAllProducts

      - run:
          name: "start webapp on local"
          command: |
            screen -d -m -s "webapp_on_local" ./build/output/_gradle_java/start.sh

      - run:
          name: "start webapp on docker"
          command: |
            ls -al /var/lib/jetty/webapps/
            cp -rf ./build/libs/_gradle_java-0.120.1.war /var/lib/jetty/webapps/ROOT.war

  bintray_build:
    machine: true
    steps:      
      - checkout
  
      - run:
          name: "archives all configured gretty products"
          command: |
            docker build --tag=120_gradle_java_image .
            docker run -d --name=120_gradle_java_container -p 80:8080 120_gradle_java_image
            curl http://localhost:80/
            curl http://localhost:80/hello
            docker stop 120_gradle_java_container

workflows:
  build:
    jobs:
      - project_build
      - local_build
      - bintray_build