# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/openjdk:11-jdk
      - image: azul/zulu-openjdk:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install tools
      - run: apt-get update -y
      - run: apt-get install -y unzip wget

      # about Gradle
      - run: ./gradlew --version

      - run:
          name: "Check project libraries"
          command: |
            cp ./jcenter.properties.sample $HOME/jcenter.properties
            ./gradlew check
            ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: 
          name: "compile, test and run the application"
          command: |
            ./gradlew compileJava
            ./gradlew run
            ./gradlew clean test

      - run:
          name: "build application"
          command: |
            ./gradlew clean build installDist

      - run: 
          name: "run application to OS"
          command: |
            ./build/install/_gradle_java/bin/_gradle_java

      - run:
          name: "test the application from jcenter"
          command: |
            rm -rf _gradle_java-0.117.1 
            wget https://dl.bintray.com/cnruby/gradle_java_jcenter/de/iotoi/_gradle_java/0.117.1/_gradle_java-0.117.1.zip
            unzip _gradle_java-0.117.1.zip
            ./_gradle_java-0.117.1/bin/basic_117

