# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: jetty:9.4.35-jre11
        user: root
      # https://stackoverflow.com/questions/50320263/change-user-on-circleci

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:      
      # install tool screen
      - run: 
          name: install tool screen
          command: |
            whoami          

      - checkout

      # /var/lib/jetty/repo
      - run: java -version
      # /var/lib/jetty/repo/build.gradle
      - run: ls -al ./build.gradle

      # Download and cache dependencies
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
          - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
          - gradle-repo-v1-{{ .Branch }}-
          - gradle-repo-v1-

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: "build application"
          command: |
            whoami
