name: Create Release for GitHub

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: up_to_basic_111
          release_name: Release to all the project `basic_111`
          body: |
            All projects in this Release
            - Lesson 101..=111
            - Lesson 000..=002
          draft: false
          prerelease: false
