name: Release--basic_112--for--GitHub

on: 
  push:
    branches:
    # branches-ignore:
      - basic_112

jobs:
  build:
    name: Create--Release--basic_112
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_112"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: basic__112__01
          release_name: Project--"basic_112"--for--The--Release
          body: |
            ### PROJECT IN THIS RELEASE
            - develop simple web app with docker and tomcat
            
            ### USING THE PROJECT

            ```bash
              # DO (download the zip file)
              wget https://github.com/cnruby/gradle_java/archive/basic__112__01.zip

              # DO (unzip the file)
              unzip gradle_java-basic__112__01.zip && cd gradle_java-basic__112__01

              # DO (build the application)
              ./gradlew clean build

              # DO (create a docker image)
              docker build --tag=112_gradle_java .

              # DO (run a docker container with Java Web App)
              docker run -p 80:8080 112_gradle_java

              # DO (use the web application)
              google-chrome http://localhost:80/
                  # >> Result
                  Hello Tomcat!

              google-chrome http://localhost:80/hello
                  # >> Result
                  [7,7,7,7,0]
            ```
          draft: false
          prerelease: false
