name: Release--basic_116

on: 
  push:
    branches:
    # branches-ignore:
      - basic_116

jobs:
  build:
    name: Create--Release--basic_116
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_116"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.116.1
          release_name: Project--"basic_116"--for--The--Release
          body: |
            ### ABOUT
            - develop simple Java application with Gradle and GitHub Actions CI

            ### USAGE
            ```bash
              # DO (download the zip file)
              wget https://github.com/cnruby/gradle_java/archive/v0.116.1.zip -O gradle_java-0.116.1.zip

              # DO (unzip the file)
              unzip gradle_java-0.116.1.zip && cd gradle_java-0.116.1

              ```bash
              # 0. View the Codes
              cat ./build.gradle
              cat ./jcenter.properties.sample
              cat ./gradle.properties

              # 1. Run all checks
              cp ./jcenter.properties.sample ~/jcenter.properties
              ./gradlew check
              ./gradlew dependencies

              # 2. Use the project task "propertiesCommand"              
              ./gradlew propertiesCommand -PBINTRAY_USER=username_cmd -PBINTRAY_API_KEY=1234567890qwertyuiopasdfghjklzxcvbnm1234 -PGPG_PASSPHRASE=password_cmd

              # 3. Use the project task "propertiesGradle"              
              ./gradlew propertiesGradle

              # 4. Use the project task "propertiesGroovy"
              ./gradlew propertiesGroovy

              # 5. Use the project task "propertiesSystem"
              export BINTRAY_USER=username
              export BINTRAY_API_KEY=1234567890qwertyuiopasdfghjklzxcvbnm1234
              export GPG_PASSPHRASE=password
              ./gradlew propertiesSystem
            ```
          draft: false
          prerelease: false
