name: Release--basic_122

on: 
  push:
    # branches:
    branches-ignore:
      - basic_122

jobs:
  build:
    name: Create--Release--"basic_122"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_122"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.122.1
          release_name: Project--"basic_122"--for--The--Release
          body: |
            ### ABOUT
            - How to Run Web Application
            
            ### USAGE            
            ```bash
              # 0. Download and Unzip the project and etc.

                # DO (download the zip file)
                wget https://github.com/cnruby/gradle_java/archive/v0.122.1.zip -O gradle_java-0.122.1.zip

                # DO (unzip the file)
                unzip gradle_java-0.122.1.zip && cd gradle_java-0.122.1

                # DO (check the web application)
                ./gradlew -q check
                    # >> Result: nothing
                
              # 1. Run the web project's application

                # DO (run the web application)
                ./gradlew clean build
                ./gradlew appRun

              # 2. Run the web project's application as-is

                # DO (Install the project as a distribution as-is)
                ./gradlew archiveAllProducts

                # DO (run the web application for Ubuntu OS)
                ./build/output/_gradle_java/start.sh

                # DO (run the web application for Windows OS)
                ./build/output/_gradle_java/start.bat

              # 3. Run the web application as war
                ./gradlew appRunWar
            ```
          draft: false
          prerelease: false
