name: Release--basic_101--for--GitHub

on: 
  push:
    branches:
    # branches-ignore:
      - basic_101

jobs:
  build:
    name: Create--Release--basic_101
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_101"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: basic__101__01
          release_name: Project--"basic_101"--for--The--Release
          body: |
            ### PROJECT IN THIS RELEASE
            - develop simple java app with the command `javac` and `java`
            
            ### USING THIS PROJECT

            ```bash
              # DO (download the zip file)
              wget https://github.com/cnruby/gradle_java/archive/basic__101__01.zip

              # DO (unzip the file)
              unzip basic__101__01.zip && cd gradle_java-basic__101__01

              # DO (build and run the application `Hello`)
              javac Hello.java
              java Hello

              # DO (build and run the application `Nihao`)
              javac -d ./buildSrc Nihao.java
              java -cp ./buildSrc Nihao
              
              # DO (build and run the application `App`)
              javac -d ./build ./src/App.java
              java -cp ./build App
            ```
          draft: false
          prerelease: false
