name: Release--basic_121

on: 
  push:
    # branches:
    branches-ignore:
      - basic_121

jobs:
  build:
    name: Create--Release--"basic_121"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_121"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.121.1
          release_name: Project--"basic_121"--for--The--Release
          body: |
            ### ABOUT
            - How to Publish Application to jcenter
            
            ### USAGE            
            ```bash
              # 0. Download and Unzip the project and etc.

                # DO (download the zip file)
                wget https://github.com/cnruby/gradle_java/archive/v0.121.1.zip -O gradle_java-0.121.1.zip

                # DO (unzip the file)
                unzip gradle_java-0.121.1.zip && cd gradle_java-0.121.1

                # DO (copy a JCenter's username and password sample file)
                cp ./jcenter.properties.sample ~/jcenter.properties
                
                # DO (check the application `App`)
                ./gradlew -q check
                    # >> Result: nothing
                
              # 1. Run the java project's application

                # DO (run the application `App`)
                ./gradlew -q run
                    # >> Result
                    Hello world.

              # 2. Run the java project's application as-is

                # DO (Install the project as a distribution as-is)
                ./gradlew installDist

                # DO (run the application `App` for Ubuntu OS)
                ./build/install/_gradle_java/bin/_gradle_java

                # DO (run the application `App` for Windows OS)
                ./build/install/_gradle_java/bin/_gradle_java.bat

              # 3. Run the java application from bintray.com
                wget https://dl.bintray.com/cnruby/gradle_java_jcenter/de/iotoi/_gradle_java/0.117.1/_gradle_java-0.117.1.zip
                unzip _gradle_java-0.117.1.zip
                ./_gradle_java-0.117.1/bin/basic_117
                    # >> Result
                    Hello world.
            ```
          draft: false
          prerelease: false
