name: Release--basic_119

on: 
  push:
    branches:
    # branches-ignore:
      - basic_119

jobs:
  build:
    name: Create--Release--"basic_119"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_119"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.119.1
          release_name: Project--"basic_119"--for--The--Release
          body: |
            ### ABOUT
            - develop simple Java application with Gradle
            
            ### USAGE
            ```bash
              # DO (download the zip file)
              wget https://github.com/cnruby/gradle_java/archive/v0.119.1.zip -O gradle_java-0.119.1.zip

              # DO (unzip the file)
              unzip gradle_java-0.119.1.zip && cd gradle_java-0.119.1

              # DO (build and run the subproject `app`)
              ./gradlew -q app:run

              # DO (Use and Test The Library from the Website `bintrag.com)
              if [ ! -d "libs" ]; then
                mkdir libs
              fi
              wget -P ./libs/ https://dl.bintray.com/cnruby/gradle_java_jcenter/de/iotoi/basic_118/0.118.1/basic_118-0.118.1.jar
              cp -f app/build.gradle.m1 app/build.gradle
              ./gradlew -q app:run
                  
              # DO (Use The Library from the `JCenter`)
              cp -f app/build.gradle.m2 app/build.gradle
              ./gradlew -q app:run

            - name: "Use a Library Package from Maven Local"
              cp -f app/build.gradle.m3 app/build.gradle
              ./gradlew clean build publishToMavenLocal
              ./gradlew -q app:run
            ```
          draft: false
          prerelease: false
