name: Release--basic_123

on: 
  push:
    branches:
    # branches-ignore:
      - basic_123

jobs:
  build:
    name: Create--Release--"basic_123"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout--Code
        uses: actions/checkout@v2
      - name: Create--Release--for--Branch--"basic_123"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.123.1
          release_name: Project--"basic_123"--for--The--Release
          body: |
            ### ABOUT
            - develop simple Java application with Gradle
            
            ### USAGE
            ```bash
              # DO (download the zip file)
              wget https://github.com/cnruby/gradle_java/archive/v0.123.1.zip -O gradle_java-0.123.1.zip

              # DO (unzip the file)
              unzip gradle_java-0.123.1.zip && cd gradle_java-0.123.1


              # 1. Usage for the project

              # DO (build and run the subproject `app`)
              ./gradlew -q app:run


              # 2. Usage Subproject `app` for OS

              # DO (install the subproject `app` as a distribution as-is)
              ./gradlew app:installDist

              # DO (run application for the subproject `app` for Ubuntu OS)
              ./codename/app/build/install/app/bin/basic_123

              # DO (run application for the subproject `app` for Windows OS)
              ./codename/app/build/install/app/bin/basic_123.bat
            ```
          draft: false
          prerelease: false
