# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: CI--basic_119

# on: [push]
on: 
  push:
    branches:
    # branches-ignore:
      - basic_119

jobs:
  build:
    name: Build--Java--App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set--up--JDK--11}
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check--the--project
      run: |
        cp ./jcenter.properties.sample ~/jcenter.properties
        ./gradlew check
        ./gradlew dependencies

    - name: compile, test and run the application
      run: |
        ./gradlew compileJava
        ./gradlew run
        ./gradlew clean test

    - name: "run application on project"
      run: |
          ./gradlew -q app:run

    - name: "Use and Test The Library from the Website `bintrag.com"
      run: |
          if [ ! -d "libs" ]; then
            mkdir libs
          fi
          wget -P ./libs/ https://dl.bintray.com/cnruby/gradle_java_jcenter/de/iotoi/basic_118/0.118.1/basic_118-0.118.1.jar
          cp -f app/build.gradle.m1 app/build.gradle
          ./gradlew -q app:run
          
    - name: "Use The Library from the `JCenter`"
      run: |
          cp -f app/build.gradle.m2 app/build.gradle
          ./gradlew -q app:run

    - name: "Use a Library Package from Maven Local"
      run: |
          cp -f app/build.gradle.m3 app/build.gradle
          ./gradlew clean build publishToMavenLocal
          ./gradlew -q app:run
