# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: CI--basic_120

# on: [push]
on: 
  push:
    branches:
    # branches-ignore:
      - basic_120

jobs:
  build:
    name: Build--Java--App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set--up--JDK--11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: install tools
      run: |
        whoami
        cat /etc/*-release
        sudo apt update -y
        sudo apt install screen wget unzip netcat -y
        screen –version
        wget --version
        unzip --version

    - name: Check--the--project
      run: |
        cp ./jcenter.properties.sample ~/jcenter.properties
        ./gradlew check
        ./gradlew dependencies


    - name: build application
      run: |
        whoami
        cp ./jcenter.properties.sample ~/jcenter.properties
        ./gradlew clean build

    - name: start webapp on project
      run: |
        screen -d -m -s "webapp_on_project" ./gradlew jettyStart

    - name: browse the website
      run: |
        sleep 5 && nc -vz localhost 8080
        curl http://127.0.0.1:8080/
        curl http://127.0.0.1:8080/hello
        ./gradlew jettyStop