# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: CI--basic_117

# on: [push]
on: 
  push:
    branches:
    # branches-ignore:
      - basic_117

jobs:
  build:
    name: Build--Java--App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set--up--JDK--11}
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check--the--project
      run: |
        cp ./jcenter.properties.sample ~/jcenter.properties
        ./gradlew check
        ./gradlew dependencies

    - name: compile, test and run the application
      run: |
        ./gradlew compileJava
        ./gradlew run
        ./gradlew clean test
        
    - name: build application
      run: |
        ./gradlew clean build installDist

    - name: run application to OS
      run: |
        ./build/install/_gradle_java/bin/_gradle_java

    - name: test the application from jcenter
      run: |
        wget https://dl.bintray.com/cnruby/gradle_java_jcenter/de/iotoi/basic_117/0.117.2/basic_117-0.117.2.zip
        unzip basic_117-0.117.2.zip
        ./_gradle_java-0.117.2/bin/_gradle_java