on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v0.0.111' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release for GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release basic_111 ${{ github.ref }}
          body: |
            To branch baisc_111 in this Release
            - Lesson 101..=111
            - Lesson 000..=002
          draft: false
          prerelease: false